//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace werty.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSupplier
    {
        public int IDTypeSupplier { get; set; }
        public string title { get; set; }
    }
}
